### ISSUE TITLE
Cannot be installed

### ISSUE THREAD

**Issue by Atulin** [jshackles/Enhanced_Steam_Firefox#117]
Firefox 59

When trying basic installation, it throws this error:
![image](https://user-images.githubusercontent.com/11233299/36942193-de8c1802-1f6c-11e8-8c73-3c1e7c1466b5.png)

When trying manual installation, it throws this one:
![image](https://user-images.githubusercontent.com/11233299/36942200-fa22758e-1f6c-11e8-81a3-3c1ef7717b26.png)

Any chance of fixing the issue, or will ES be Chrome-only in the future?

**Comment by jshackles** [comment]
If you are having issues installing from the website, the same version can be installed directly from the Firefox Addons page

https://addons.mozilla.org/en-US/firefox/addon/enhanced-steam/

**Comment by Atulin** [comment]
Thanks, might consider making that where the link goes, as it is with Chrome version. I had no idea ES is on Firefox Addons, honestly.
