### ISSUE TITLE
"You own this game since" disappeared since site update

### ISSUE THREAD

**Issue by kazerniel** [jshackles/Enhanced_Steam_Firefox#59]
I just realised that I haven't seen this line (or some similar phrasing) on the page of owned games since that large Steam site update a few months ago. It would be nice to have it back :)

**Comment by jshackles** [comment]
Good catch.  This appears to have been caused when Steam changed the layout of the account page.  I'll get this updated and working again in the next release.

**Comment by kazerniel** [comment]
Thank you!
