### ISSUE TITLE
Can crash Firefox on at least some titles

### ISSUE THREAD

**Issue by apocalyptech** [jshackles/Enhanced_Steam_Firefox#61]
With Enhanced Steam enabled on my browser, I can reproduce a browser crash 100% of the time by viewing, for instance:

http://store.steampowered.com/app/344510/

I seem to think there were some other more recent games which were doing it as well, but that one at least seems to do the trick.  Tried with both the version available for download from the site, and the current XPI from git.

**Comment by jshackles** [comment]
Do you have the latest update for Firefox that was released on Jan 26th?  (35.0.1)

There was a bug in version 35.0 that caused the browser to crash, but Mozilla corrected it in 35.0.1, see the release notes here: https://www.mozilla.org/en-US/firefox/35.0.1/releasenotes/

**Comment by apocalyptech** [comment]
Oh!  Good to know - No, I'm still on 35.0.  I'll get that updated and let you know.  (Looks like 35.0.1 isn't yet in Fedora21's repos, so it might be a few days.)

Thanks!

**Comment by apocalyptech** [comment]
Okay, finally got on 35.0.1, and can confirm that (as expected) the Firefox update has fixed this issue for me.

Thanks!  I'll close this out.
