### ISSUE TITLE
[Feature request] Add option to hide "someUser added someGame to their favorites" from Friend Activity feed.

### ISSUE THREAD

**Issue by markoii** [jshackles/Enhanced_Steam_Firefox#62]
Sometimes a friend adds a slur of games to their favorites and it clogs the Friend Activity feed. It gets even worse when two or more friends do that at the same time! :)

It'd be nice if there was an option for hiding all "added to favorites" notifications. It wouldn't hurt if there was the same option to hide "someUser now ownes someGame" too.

**Comment by jshackles** [comment]
Actually, this can already be done without Enhanced Steam.  At the top of the activity page there is a small link titled "Friend Activity Settings" that links to http://steamcommunity.com/my/blotteredit where you can check which items you'd like to see on that page.

Simply uncheck the box in the "A player from my friends list:" section labeled "Adds a game to his or her wishlist?" and hit "Save changes" at the bottom.  :)

You can use this page to show or hide pretty much everything that gets put on the activity page.

**Comment by markoii** [comment]
Thanks for the reply, but that's not what I'm looking for. I'm talking about adding to Favorites from Community pages such as Greenlight. Those "someUser added someGame to their favorites" notifications in Friend Activity feed started showing up recently... and there is no option on the blotter page you've linked.

**Comment by jshackles** [comment]
The option you are looking for is at the bottom of the "A player from my friends list:" section, and is labeled "Favorites an item?".  Unchecking this box and saving your settings should remove these notifications from your activity page.

**Comment by markoii** [comment]
Oh, you said "Adds a game to his or her wishlist?", so I presumed there still isn't an option for favorites... at least there wasn't before, as I recall. Sorry for being blind as a bat and not looking more closely at the blotter page. Thanks!
