### ISSUE TITLE
Buy Remaining Cards From Market - No Longer Working.

### ISSUE THREAD

**Issue by WasabiIceCream** [jshackles/Enhanced_Steam_Firefox#71]
Using WaterFox version 38.
When I hit the "Buy Remaining Cards From Market", the remaining cards are just listed with "Error" beside them.

![capture](https://cloud.githubusercontent.com/assets/12481327/7669717/47d9255e-fc50-11e4-9fe7-8db3a83e0c62.PNG)

![capture2](https://cloud.githubusercontent.com/assets/12481327/7669718/4933bdce-fc50-11e4-9fbd-2b0ad81e32ce.PNG)

**Comment by jshackles** [comment]
This is not a function of Enhanced Steam.  That button must be part of another extension you have installed.
