### ISSUE TITLE
Signed version

### ISSUE THREAD

**Issue by z0rc** [jshackles/Enhanced_Steam_Firefox#72]
Signed version of Enhanced Steam is needed before Firefox 41. See https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by m3Lith** [comment]
[ES for FF is no more](http://www.enhancedsteam.com/blog/support-ending-for-firefox-browsers/).

**Comment by z0rc** [comment]
All right, just removed ES completely. Author should consider adding note about this into readme.
